### ISSUE TITLE
sdist creates "settings" package

### ISSUE THREAD

**Issue by jayvdb** [lddubeau/django-cache-management#1]
Using `find_packages()` finds top level directories like "settings", which then are installed, and causes Sphinx to create `doc/_apidoc/settings.rst`

p.s. https://pypi.org/project/django-email-integration-test/ lists a repo which isnt on GitHub

**Comment by lddubeau** [comment]
Thank you for the bug report. It should be fixed now.

**Comment by jayvdb** [comment]
@lddubeau https://github.com/lddubeau/django-email-integration-test still doesnt exist

**Comment by lddubeau** [comment]
Forgot about that one. It's there now.

**Comment by jayvdb** [comment]
Awesome; thank you!
